In [1]:
import numpy as np
import pandas as pd
df=pd.read_excel("附件/蔬菜单品日销量.xlsx", index_col=0).T
df2=pd.read_excel("2.xlsx", index_col=0)

In [2]:
df1=pd.DataFrame()
df1['总销量'] = df.iloc[:, :].sum(axis=1)
df1[['打折次数','销售次数', '平均定价', '定价汇总']]=0

                        总销量  打折次数  销售次数  平均定价  定价汇总
102900005117056   9703.1250     0     0     0     0
102900005115960  19187.2180     0     0     0     0
102900005115823   7625.0370     0     0     0     0
102900005115908   4515.3935     0     0     0     0
102900005115779  15962.7295     0     0     0     0
...                     ...   ...   ...   ...   ...
102900011036242     45.0000     0     0     0     0
102900011035849     16.5380     0     0     0     0
102900011021675      2.3880     0     0     0     0
106972776821582    128.0000     0     0     0     0
102900011036686     27.0000     0     0     0     0

[246 rows x 5 columns]

In [3]:
# 注意：由于数据有246*877000，这个代码将近需要1h，可以用i来判断进度
i=0
for product_ID in df2['product_code'].unique():
    print(i)
    i+=1
    for index, row in df2.iterrows():
        if row['product_code'] == product_ID:
            if row['is_discount'] == 0:
                df1.loc[product_ID, '打折次数']+=1
            df1.loc[product_ID, '销售次数']+=1
            df1.loc[product_ID, '定价汇总']+=row['unit_price']

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
155
156
157
158
159
160
161
162
163
164
165
166
167
168
169
170
171
172
173
174
175
176
177
178
179
180
181
182
183
184
185
186
187
188
189
190
191
192
193
194
195
196
197
198
199
200
201
202
203
204
205
206
207
208
209
210
211
212
213
214
215
216
217
218
219
220
221
222
223
224
225
226
227
228
229
230
231
232
233
234
235
236
237
238
239
240
241
242
243
244
245

In [6]:
df1.to_excel('所有单品信息（总销量-打折次数—日定价-销售次数）.xlsx', index=True)

In [11]:
# 统计合并该段时间内附件四出现的单品的损耗率
import pandas as pd

df1=pd.read_excel("所有单品信息（总销量-打折次数—日定价-销售次数）.xlsx", index_col=0) # 该文件未被包含在文件夹内，有完整版数据
df3=pd.read_excel("4_1.xlsx")
# 不需要记录单品的名称
del df3['product_name']
# 将已经统计的表添加一列‘product_code’便于合并
df1['product_code']=df1.index
df1['平均定价']=df1['定价汇总']/df1['销售次数']
merged_df = df1.merge(df3, on=['product_code', 'product_code'], how='inner')
merged_df.index=merged_df['product_code']
del merged_df['product_code']
del merged_df['定价汇总']
del df1['product_code']
merged_df.rename(columns={'loss_rate': '损耗率'}, inplace=True)
merged_df.to_excel('完整-所有单品信息（总销量-打折次数—日定价-销售次数）.xlsx', index=True)