# 本程序用于观察数据的基本特征、计算单品日销量、计算各种类蔬菜日销量

In [1]:
import numpy as np
import pandas as pd

In [2]:
# 为了方便，将附件的文件名和各附件内不同列名进行了修改（转换为英文）
df = pd.read_excel("1.xlsx", index_col=0)
df1=pd.read_excel("2.xlsx", index_col=0)
df2=pd.read_excel("3.xlsx", index_col=0)
df3=pd.read_excel("4_1.xlsx", index_col=0)

In [20]:
## 将附件一的蔬菜种类转换为数字，附件二的销售类型与打折转换为数字（可以不进行，如果要做这一步就要先把附录的列名进行修改）

# columns=["category_name"]
# mapping_dict = {}
# for column_name in columns:
#     unique_values = df[column_name].unique()
#     value_to_number = {value: number for number, value in enumerate(unique_values)}
#     mapping_dict[column_name] = value_to_number

# # Replace values in all columns with numbers
# for column_name in columns:
#     df[column_name] = df[column_name].replace(mapping_dict[column_name])

# columns=["type","is_discount"]
# mapping_dict = {}
# for column_name in columns:
#     unique_values = df1[column_name].unique()
#     value_to_number = {value: number for number, value in enumerate(unique_values)}
#     mapping_dict[column_name] = value_to_number

# # Replace values in all columns with numbers
# for column_name in columns:
#     df1[column_name] = df1[column_name].replace(mapping_dict[column_name])

## 观察数据的基本特征

In [14]:
unique_to_df1 = df1[~df1['product_code'].isin(df2['product_code'])]
unique_to_df2 = df2[~df2['product_code'].isin(df1['product_code'])]

date_unique_to_df1 = df1[~df1['sale_date'].isin(df2['sale_date'])]
date_unique_to_df2 = df2[~df2['sale_date'].isin(df1['sale_date'])]
for col in unique_to_df2['product_code'].unique():
    print(df[df['product_code'] == col])

date_unique_to_df2['sale_date'].unique()

        product_code product_name  category_code  category_name
198  102900011011782    虫草花(盒)(1)     1011010801              5
       product_code product_name  category_code  category_name
20  102900005116776         本地菠菜     1011010101              0
        product_code product_name  category_code  category_name
163  102900011032145      芜湖青椒(份)     1011010504              4
        product_code product_name  category_code  category_name
105  102900005116042            藕     1011010402              2
        product_code product_name  category_code  category_name
150  102900011023648      芜湖青椒(2)     1011010504              4

<DatetimeArray>
['2022-11-02 00:00:00', '2022-11-04 00:00:00', '2022-11-30 00:00:00',
 '2022-12-01 00:00:00', '2022-12-02 00:00:00', '2022-12-03 00:00:00']
Length: 6, dtype: datetime64[ns]

## 计算单品日销量

In [21]:
# 统计单品的日销量（缺失6天的数据）
date_unique = df1['sale_date'].unique()
product_unique = df1['product_code'].unique()
total_sales = pd.DataFrame(0, index=date_unique, columns=product_unique)  # 用来统计单品日销量
for index, row in df1.iterrows():
    saled = row['type']
    date = row['sale_date']
    kind = row['product_code']
    volume = row['volume']
    unit_price = row['unit_price']
    total_sales.at[date, kind] += volume

,102900005117056,102900005115960,102900005115823,102900005115908,102900005115779,102900011008522,102900005118824,102900005115984,102900005116530,102900005116226,...,102900011035740,102900011034538,102900011023976,102900011036266,102900011032480,102900011036242,102900011035849,102900011021675,106972776821582,102900011036686
2020-07-01,54.548,14.748,11.476,8.959,41.966,18.271,4.119,32.579,7.693,2.844,...,0,0,0.0,0,0.0,0,0.0,0.0,0,0
2020-07-02,39.810,11.228,6.806,14.275,44.873,13.548,4.342,27.056,17.345,1.667,...,0,0,0.0,0,0.0,0,0.0,0.0,0,0
2020-07-03,32.351,10.446,13.120,8.173,36.309,13.562,9.572,36.709,15.290,2.331,...,0,0,0.0,0,0.0,0,0.0,0.0,0,0
2020-07-04,45.815,9.638,28.186,13.034,51.205,15.843,3.107,43.330,14.532,3.948,...,0,0,0.0,0,0.0,0,0.0,0.0,0,0
2020-07-05,53.874,9.698,12.038,10.791,34.249,17.408,4.019,12.594,18.406,3.535,...,0,0,0.0,0,0.0,0,0.0,0.0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2023-06-26,0.000,0.000,1.420,0.000,7.971,0.000,1.973,0.573,0.000,0.000,...,3,0,0.0,0,0.0,0,0.0,0.0,0,0
2023-06-27,0.000,0.000,1.823,0.822,0.251,0.000,3.947,0.293,0.000,0.000,...,1,0,0.0,0,0.0,0,0.0,0.0,0,1
2023-06-28,0.000,0.000,5.553,2.701,0.000,0.000,2.451,0.000,0.000,0.000,...,0,0,0.0,0,0.0,0,0.0,0.0,0,0
2023-06-29,0.000,0.000,4.687,0.000,2.904,0.000,3.477,0.000,0.000,0.000,...,0,0,0.0,0,0.0,0,0.0,0.0,0,1
2023-06-30,0.000,0.000,7.036,0.000,0.000,0.000,3.780,0.000,0.000,0.000,...,2,0,0.0,0,0.0,0,0.0,0.0,0,1

### 填补单品日销量缺失数据

In [22]:
# 对于单品日销量数据缺失的6天数据，由于数据缺失都发生在2022年，于是我们采取用前两年同天的数据进行填补。
# （如果某类单品在前两年同一天均有出售，我们便将今年的销售量取为前两年均值）
dates=['2022-11-02 00:00:00', '2022-11-04 00:00:00', '2022-11-30 00:00:00',
 '2022-12-01 00:00:00', '2022-12-02 00:00:00', '2022-12-03 00:00:00']
dates_datetime = pd.to_datetime(dates)

for date in dates_datetime:
    date1 = date - pd.DateOffset(years=1)
    date2 = date - pd.DateOffset(years=2)
    for col in total_sales.columns:
        if total_sales.loc[date2][col] != 0 and total_sales.loc[date1][col] != 0:
            total_sales.loc[date, col]=(total_sales.loc[date2][col]+total_sales.loc[date1][col])/2
            
total_sales=total_sales.sort_index().fillna(0)
total_sales.to_excel('蔬菜单品日销量.xlsx', index=True)

,102900005117056,102900005115960,102900005115823,102900005115908,102900005115779,102900011008522,102900005118824,102900005115984,102900005116530,102900005116226,...,102900011035740,102900011034538,102900011023976,102900011036266,102900011032480,102900011036242,102900011035849,102900011021675,106972776821582,102900011036686
2020-07-01,54.548,14.748,11.476,8.959,41.966,18.271,4.119,32.579,7.693,2.844,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2020-07-02,39.810,11.228,6.806,14.275,44.873,13.548,4.342,27.056,17.345,1.667,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2020-07-03,32.351,10.446,13.120,8.173,36.309,13.562,9.572,36.709,15.290,2.331,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2020-07-04,45.815,9.638,28.186,13.034,51.205,15.843,3.107,43.330,14.532,3.948,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2020-07-05,53.874,9.698,12.038,10.791,34.249,17.408,4.019,12.594,18.406,3.535,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2023-06-26,0.000,0.000,1.420,0.000,7.971,0.000,1.973,0.573,0.000,0.000,...,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2023-06-27,0.000,0.000,1.823,0.822,0.251,0.000,3.947,0.293,0.000,0.000,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
2023-06-28,0.000,0.000,5.553,2.701,0.000,0.000,2.451,0.000,0.000,0.000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2023-06-29,0.000,0.000,4.687,0.000,2.904,0.000,3.477,0.000,0.000,0.000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
2023-06-30,0.000,0.000,7.036,0.000,0.000,0.000,3.780,0.000,0.000,0.000,...,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0

## 计算各种类蔬菜日销量

In [48]:
# 统计各类蔬菜的日销量
date_unique = total_sales.index.unique()
product_unique = df['category_name'].unique()
cate_sale = pd.DataFrame(0, index=date_unique, columns=product_unique)

for index, row in total_sales.iterrows():
    for kind in df['category_name'].unique():
        for col in total_sales.columns:
            if col in df[df['category_name']==kind]['product_code'].values:
                cate_sale.at[index, kind] += row[col]

name = ['花叶类', '花菜类', '水生根茎类', '茄类', '辣椒类', '食用菌']
cate_sale.columns = name
cate_sale.to_excel('蔬菜品类日销量.xlsx', index=True)